exports.SOCKET_EVENT = {
  VIEWER_STATUA: {
    PDF_LOAD_SUCCESS: 'PDF_LOAD_SUCCESS',
    PDF_LOAD_FAIL: 'PDF_LOAD_FAIL',
    VIEWER_IDLE: 'VIEWER_IDLE'
  },
  FILE_INDEX: {
    SET_FILE_INDEX: 'SET_FILE_INDEX',
    GET_FILE: 'GET_FILE',
    GET_LATEST_FILE: 'GET_LATEST_FILE'
  }
}
