export const SEARCH_RESULT_TYPE = {
  NORMAL: 'NORMAL',
  NO_KEYWORD: 'NO_KEYWORD',
  NO_RESULT: 'NO_RESULT',
}

export const SEARCH_MODE_TYPE = {
  FILE_LIST: 'filelist',
  SONG_LIST: 'songlist'
}

export const PDF_STATUS = {
  IDLE: 'IDLE',
  ERROR: 'ERROR',
  ON_LOAD: 'ON_LOAD',
  ON_LOAD_ERROR: 'ON_LOAD_ERROR',
  ON_LOAD_SUCCESS: 'ON_LOAD_SUCCESS',
  ON_SOURCE_ERROR: 'ON_SOURCE_ERROR',
  ON_RENDER_SUCCESS: 'ON_RENDER_SUCCESS',
}

export const RENDER_SIZE_BY_HEIGHT = 'renderSizeByHeight'

export const RENDER_SIZE_BY_WIDTH = 'renderSizeByWidth'

export const PDF_LOAD_SUCCESS = 'PDF_LOAD_SUCCESS'
