export const SEARCH_RESULT_TYPE = {
  NORMAL: 'NORMAL',
  NO_KEYWORD: 'NO_KEYWORD',
  NO_RESULT: 'NO_RESULT',
}

export const SEARCH_MODE_TYPE = {
  FILE_LIST: 'filelist',
  SONG_LIST: 'songlist'
}

export const PDF_STATUS = {
  IDLE: 'IDLE',
  ERROR: 'ERROR',
  ON_LOAD: 'ON_LOAD',
  ON_LOAD_ERROR: 'ON_LOAD_ERROR',
  ON_LOAD_SUCCESS: 'ON_LOAD_SUCCESS',
  ON_SOURCE_ERROR: 'ON_SOURCE_ERROR',
  ON_RENDER_SUCCESS: 'ON_RENDER_SUCCESS',
}

export const SOCKET_EVENT = {
  VIEWER_STATUA: {
    PDF_LOAD_SUCCESS: 'PDF_LOAD_SUCCESS',
    PDF_LOAD_FAIL: 'PDF_LOAD_FAIL',
    VIEWER_IDLE: 'VIEWER_IDLE'
  },
  FILE_INDEX: {
    SET_FILE_INDEX: 'SET_FILE_INDEX',
    GET_FILE: 'GET_FILE',
    GET_LATEST_FILE: 'GET_LATEST_FILE'
  },
  PAGE_ACTIONS: {
    SET_NEXT_PAGE: 'SET_NEXT_PAGE',
    SET_PREV_PAGE: 'SET_PREV_PAGE'
  }
}

export const RENDER_SIZE_BY_HEIGHT = 'renderSizeByHeight'

export const RENDER_SIZE_BY_WIDTH = 'renderSizeByWidth'
